### ISSUE TITLE
Seasonality plot for ^IXIC and other US indices for last few days of the year is strange

### ISSUE THREAD

**Issue by tangkb** [kumeS/seasonalityPlot#1]
Hi Satoshi,
Thank you for creating such a nice package.
I noticed that the seasonality plot seemed to be strange for Dec.
The Dec return seemed to be too high, especially with the spiked tail for the last few days.
I am using another R package (SIT) to generate seasonality table and your Dec return seemed to be too high.
I am too noob to check and understand the scipts.
Thanks you for reading my post.
![111](https://github.com/kumeS/seasonalityPlot/assets/8244207/0f285c6b-e35b-4ecf-9b04-996d6dd30918)

**Comment by kumeS** [comment]
@tangkb 
Hi tangkb,

Thanks for your kind comments.
As you well know, there is an apparent drift at the end of December.
I have provided some modification to this package to prevent that case in NASDAQ (^IXIC).
I have also published the new version of this package as seasonalityPlot - v1.1.0 in GitHub (https://github.com/kumeS/seasonalityPlot/releases/tag/v1.1.0) and just submitted to CRAN.
Please enjoy the new package of seasonalityPlot.

Thank you for your suggestion and supports.

Best regards,

Satoshi

<img width="539" alt="IXIC_pic" src="https://github.com/kumeS/seasonalityPlot/assets/10130812/5d0d4861-578c-463f-99cf-ae22651c9ca3">
