### ISSUE TITLE
Suggestion to add an option to use adjusted close for seasonplot

### ISSUE THREAD

**Issue by tangkb** [kumeS/seasonalityPlot#2]
Hi Satoshi,
Thanks again for your very useful package.
I believe the data used to draw the seasonplot is normal close of the stock.
It will be good if we have the option to use adjusted close since the data is available from quantmod/yahoo.
Since many stocks have good dividends, the seasonplot should look different with the close adjusted for dividends.
I hope that you can consider adding an option to use adjusted close.
Thank your for reading suggestion.

**Comment by kumeS** [comment]
Hi @tangkb 
Thank you for your kind suggestion.
I will consider your idea to improve this package.
I will get back to you when I have solved this problem.

**Comment by kumeS** [comment]
Hi @tangkb I have updated this package and added a new feature. Please enjoy it! Satoshi

**Comment by kumeS** [comment]
@tangkb Please refer to the new version page of seasonalityPlot v1.2.1 on CRAN.
https://cran.r-project.org/web/packages/seasonalityPlot/index.html

**Comment by tangkb** [comment]
Hi Satoshi,
Thanks alot. Love your fantastic package alot. 
Thanks for the update.
